#!/bin/sh

if [ "x$1" = "x-usage" ]; then
    echo "Pull memo from remote."
    exit 0
fi

MEMODIR=`cat ~/.config/memo/config.toml | grep memodir | awk -F\" '{print $2}'`
echo "Pull memo from GitHub."
echo ""
echo "Target directory"
echo " - ${MEMODIR}"
echo ""
echo "= = = exec log = = ="

CURRENT_STATUS=`cd ${MEMODIR} && git status -s`
if [ "x${CURRENT_STATUS}" != "x" ]; then
    (cd ${MEMODIR} && git stash && git pull && git stash pop)
else
    (cd ${MEMODIR} && git pull)
fi
