#!/bin/sh

if [ "x$1" = "x-usage" ]; then
    echo "push memo to remote."
    exit 0
fi

MEMODIR=`cat ~/.config/memo/config.toml | grep memodir | awk -F\" '{print $2}'`
echo "Push the following content to github."
echo " - ${MEMODIR}\n"

echo "== git status =="
(cd ${MEMODIR} && git status)

echo ""
read -p "  OK? (y/N): " yn
if [ "xy" != "x${yn}" ]; then
    exit 1
fi

echo "== git commit && push =="
(cd ${MEMODIR} && git add . && git commit -am'update documents' && git push)
